---
apiVersion: v1
kind: Service
metadata:
  name:javaapp
  labels:
    app: javaapp
spec:
  type: NodePort
  selector:
    app: javaapp
  ports:
  - protocol: TCP
    port: 8080
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapp
spec:
  selector:
    matchLabels:
      app: javaapp
  replicas: 1
  template:
    metadata:
      labels:
        app: javaapp
    spec:
      containers:
      - name: javaapp
        image: thetips4you/productcatalogue:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8025
          initialDelaySeconds: 30
          timeoutSeconds: 1
