name: Python Script Workflow

on:
  push:
    branches:
      - master  # Change this to match your main branch name
  pull_request:
    branches:
      - master  # Change this to match your main branch name

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Choose the Python version you need

      - name: Install dependencies
        run: pip install requests

      - name: Run Python script
        run: python  pr_version_release.py 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: pull_requests
          path: pull_requests.txt
