name: Python Script Workflow
run-name: PR_release_version
on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master  
jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  

      - name: Install dependencies
        run: pip install requests

      - name: Run Python script
        run: python  pr_version_release.py 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pull_requests
          path: pull_requests.txt
